<?php
$wpdb->query("DROP TABLE IF EXISTS `{$tables['sponsors']}`");
$wpdb->query("CREATE TABLE IF NOT EXISTS `{$tables['sponsors']}` (
        `id` int(11) unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY,
        `name` varchar(64) NOT NULL,
        `logo` TEXT,
        `url` TEXT,
        `social` TEXT NULL,
        `about` TEXT NULL,
        `sponsor_category` varchar(24) NULL,
        `sponsor_type` varchar(24) NOT NULL DEFAULT 1,
        `created_at` DATETIME NOT NULL
    )" . $wpdb->get_charset_collate() . ";");

$sql = <<<SQL
INSERT INTO `{$tables['sponsors']}` (`id`, `name`, `logo`, `url`, `social`, `about`, `sponsor_category`, `sponsor_type`, `created_at`) VALUES
(1, 'Sponsor1', 'http://themes.pixiesquad.com/pixiehuge/orange-elite/wp-content/uploads/2017/06/8.png', 'https://themeforest.net/user/pixiesquad?ref=PixieSquad', '{"facebook":"https://themeforest.net/user/pixiesquad?ref=PixieSquad","twitter":"https://themeforest.net/user/pixiesquad?ref=PixieSquad","instagram":"https://themeforest.net/user/pixiesquad?ref=PixieSquad","youtube":"https://themeforest.net/user/pixiesquad?ref=PixieSquad","steam":"https://themeforest.net/user/pixiesquad?ref=PixieSquad","linkedin":"https://themeforest.net/user/pixiesquad?ref=PixieSquad"}', 'Roccat is the worlds 4th-largest PC vendor by 2015 unit sales.[3] Asus appears in BusinessWeek’s infoTech 100 and Asia’s Top 10 IT Companies rankings, and it ranked first in the IT.', ' Head Sponsor', '3', '2017-06-16 00:18:27'),
(2, 'Sponsor2', 'http://themes.pixiesquad.com/pixiehuge/orange-elite/wp-content/uploads/2017/06/4.png', 'https://themeforest.net/user/pixiesquad?ref=PixieSquad', '{"facebook":"https://themeforest.net/user/pixiesquad?ref=PixieSquad","twitter":"https://themeforest.net/user/pixiesquad?ref=PixieSquad","instagram":"https://themeforest.net/user/pixiesquad?ref=PixieSquad","youtube":"https://themeforest.net/user/pixiesquad?ref=PixieSquad","steam":"https://themeforest.net/user/pixiesquad?ref=PixieSquad","linkedin":"https://themeforest.net/user/pixiesquad?ref=PixieSquad"}', 'Roccat is the worlds 4th-largest PC vendor by 2015 unit sales.[3] Asus appears in BusinessWeek’s infoTech 100 and Asia’s Top 10 IT Companies rankings, and it ranked first in the IT.', 'Sponsor', '1', '2017-06-16 00:18:27'),
(3, 'Sponsor3', 'http://themes.pixiesquad.com/pixiehuge/orange-elite/wp-content/uploads/2017/06/5.png', 'https://themeforest.net/user/pixiesquad?ref=PixieSquad', '{"facebook":"https://themeforest.net/user/pixiesquad?ref=PixieSquad","twitter":"https://themeforest.net/user/pixiesquad?ref=PixieSquad","instagram":"https://themeforest.net/user/pixiesquad?ref=PixieSquad","youtube":"https://themeforest.net/user/pixiesquad?ref=PixieSquad","steam":"https://themeforest.net/user/pixiesquad?ref=PixieSquad","linkedin":"https://themeforest.net/user/pixiesquad?ref=PixieSquad"}', 'Roccat is the worlds 4th-largest PC vendor by 2015 unit sales.[3] Asus appears in BusinessWeek’s infoTech 100 and Asia’s Top 10 IT Companies rankings, and it ranked first in the IT.', 'Promoter', '3', '2017-06-16 00:18:27'),
(4, 'Sponsor4', 'http://themes.pixiesquad.com/pixiehuge/orange-elite/wp-content/uploads/2017/06/6.png', 'https://themeforest.net/user/pixiesquad?ref=PixieSquad', '{"facebook":"https://themeforest.net/user/pixiesquad?ref=PixieSquad","twitter":"https://themeforest.net/user/pixiesquad?ref=PixieSquad","instagram":"https://themeforest.net/user/pixiesquad?ref=PixieSquad","youtube":"https://themeforest.net/user/pixiesquad?ref=PixieSquad","steam":"https://themeforest.net/user/pixiesquad?ref=PixieSquad","linkedin":"https://themeforest.net/user/pixiesquad?ref=PixieSquad"}', 'Roccat is the worlds 4th-largest PC vendor by 2015 unit sales.[3] Asus appears in BusinessWeek’s infoTech 100 and Asia’s Top 10 IT Companies rankings, and it ranked first in the IT.', 'Sponsor', '2', '2017-06-16 00:18:27'),
(5, 'Sponsor5', 'http://themes.pixiesquad.com/pixiehuge/orange-elite/wp-content/uploads/2017/06/7.png', 'https://themeforest.net/user/pixiesquad?ref=PixieSquad', '{"facebook":"https://themeforest.net/user/pixiesquad?ref=PixieSquad","twitter":"https://themeforest.net/user/pixiesquad?ref=PixieSquad","instagram":"https://themeforest.net/user/pixiesquad?ref=PixieSquad","youtube":"https://themeforest.net/user/pixiesquad?ref=PixieSquad","steam":"https://themeforest.net/user/pixiesquad?ref=PixieSquad","linkedin":"https://themeforest.net/user/pixiesquad?ref=PixieSquad"}', 'Roccat is the worlds 4th-largest PC vendor by 2015 unit sales.[3] Asus appears in BusinessWeek’s infoTech 100 and Asia’s Top 10 IT Companies rankings, and it ranked first in the IT.', 'Sponsor', '2', '2017-06-16 00:18:27'),
(6, 'Sponsor6', 'http://themes.pixiesquad.com/pixiehuge/orange-elite/wp-content/uploads/2017/06/1.png', 'https://themeforest.net/user/pixiesquad?ref=PixieSquad', '{"facebook":"https://themeforest.net/user/pixiesquad?ref=PixieSquad","twitter":"https://themeforest.net/user/pixiesquad?ref=PixieSquad","instagram":"https://themeforest.net/user/pixiesquad?ref=PixieSquad","youtube":"https://themeforest.net/user/pixiesquad?ref=PixieSquad","steam":"https://themeforest.net/user/pixiesquad?ref=PixieSquad","linkedin":"https://themeforest.net/user/pixiesquad?ref=PixieSquad"}', 'Roccat is the worlds 4th-largest PC vendor by 2015 unit sales.[3] Asus appears in BusinessWeek’s infoTech 100 and Asia’s Top 10 IT Companies rankings, and it ranked first in the IT.', 'Sponsor', '2', '2017-06-16 00:18:27');
SQL;
$wpdb->query($sql);