<?php
$wpdb->query("DROP TABLE IF EXISTS `{$tables['matches']}`");
$wpdb->query("CREATE TABLE IF NOT EXISTS `{$tables['matches']}` (
        `id` int(11) unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY,
        `slug` varchar(64) NOT NULL,
        `game` varchar(64) NOT NULL,
        `startdate` DATETIME NOT NULL,
        `score_a` VARCHAR(6) DEFAULT NULL,
        `score_b` VARCHAR(6) DEFAULT NULL,
        `status` int(11) NULL DEFAULT NULL,
        `team_a_id` int(11) unsigned NOT NULL references {$tables['teams']}(id),
        `team_a_name` varchar(64) NOT NULL,
        `team_a_logo` TEXT NOT NULL,
        `team_b_id` int(11) unsigned NOT NULL references {$tables['teams']}(id),
        `team_b_name` varchar(64) NOT NULL,
        `team_b_logo` TEXT NOT NULL,
        `stream` int(11) unsigned NOT NULL references {$tables['streams']}(id),
        `details` TEXT NULL,
        `maps` TEXT NULL,
        `created_at` DATETIME NOT NULL
    )" . $wpdb->get_charset_collate() . ";");

$sql = <<<SQL
INSERT INTO `{$tables['matches']}` (`id`, `slug`, `game`, `startdate`, `score_a`, `score_b`, `status`, `team_a_id`, `team_a_name`, `team_a_logo`, `team_b_id`, `team_b_name`, `team_b_logo`, `stream`, `details`, `maps`, `created_at`) VALUES
(1, '1-midnight-turtles-rhyno-domynos', 'Vainglory', '2017-06-16 02:05:00', '0', '0', 1, 1, 'Midnight Turtles', 'http://themes.pixiesquad.com/pixiehuge/orange-elite/wp-content/uploads/2017/06/logo2.png', 2, 'Rhyno Domynos', 'http://themes.pixiesquad.com/pixiehuge/orange-elite/wp-content/uploads/2017/06/intz.png', 0, '{"tournament_name":"SL i-League StarSeries S3","tournament_description":"Season 2 April 2017","best_of":"3","read_article":"https:\\/\\/www.hltv.org\\/news\\/20717\\/sk-invited-to-esl-one-new-york","maps":"{\\"de dust 2\\":{\\"team_a\\":\\"\\",\\"team_b\\":\\"\\"},\\"de inferno\\":{\\"team_a\\":\\"\\",\\"team_b\\":\\"\\"},\\"de nuke\\":{\\"team_a\\":\\"\\",\\"team_b\\":\\"\\"}}"}', NULL, '2017-06-16 00:05:59'),
(2, '2-midnight-turtles-rhyno-domynos', 'Vainglory', '2017-06-16 02:05:00', '0', '0', 1, 1, 'Midnight Turtles', 'http://themes.pixiesquad.com/pixiehuge/orange-elite/wp-content/uploads/2017/06/logo2.png', 2, 'Rhyno Domynos', 'http://themes.pixiesquad.com/pixiehuge/orange-elite/wp-content/uploads/2017/06/intz.png', 0, '{"tournament_name":"SL i-League StarSeries S3","tournament_description":"Season 2 April 2017","best_of":"3","read_article":"https:\\/\\/www.hltv.org\\/news\\/20717\\/sk-invited-to-esl-one-new-york","maps":"{\\"de dust 2\\":{\\"team_a\\":\\"\\",\\"team_b\\":\\"\\"},\\"de inferno\\":{\\"team_a\\":\\"\\",\\"team_b\\":\\"\\"},\\"de nuke\\":{\\"team_a\\":\\"\\",\\"team_b\\":\\"\\"}}"}', NULL, '2017-06-16 00:05:59'),
(3, '3-midnight-turtles-rhyno-domynos', 'Vainglory', '2017-06-16 02:05:00', '0', '0', 1, 1, 'Midnight Turtles', 'http://themes.pixiesquad.com/pixiehuge/orange-elite/wp-content/uploads/2017/06/logo2.png', 2, 'Rhyno Domynos', 'http://themes.pixiesquad.com/pixiehuge/orange-elite/wp-content/uploads/2017/06/intz.png', 0, '{"tournament_name":"SL i-League StarSeries S3","tournament_description":"Season 2 April 2017","best_of":"3","read_article":"https:\\/\\/www.hltv.org\\/news\\/20717\\/sk-invited-to-esl-one-new-york","maps":"{\\"de dust 2\\":{\\"team_a\\":\\"\\",\\"team_b\\":\\"\\"},\\"de inferno\\":{\\"team_a\\":\\"\\",\\"team_b\\":\\"\\"},\\"de nuke\\":{\\"team_a\\":\\"\\",\\"team_b\\":\\"\\"}}"}', NULL, '2017-06-16 00:05:59'),
(4, '4-midnight-turtles-rhyno-domynos', 'Vainglory', '2017-06-16 02:05:00', '1', '0', 1, 1, 'Midnight Turtles', 'http://themes.pixiesquad.com/pixiehuge/orange-elite/wp-content/uploads/2017/06/logo2.png', 2, 'Rhyno Domynos', 'http://themes.pixiesquad.com/pixiehuge/orange-elite/wp-content/uploads/2017/06/intz.png', 0, '{"tournament_name":"SL i-League StarSeries S3","tournament_description":"Season 2 April 2017","best_of":"3","read_article":"https:\\/\\/www.hltv.org\\/news\\/20717\\/sk-invited-to-esl-one-new-york","maps":"{\\"de dust 2\\":{\\"team_a\\":\\"\\",\\"team_b\\":\\"\\"},\\"de inferno\\":{\\"team_a\\":\\"\\",\\"team_b\\":\\"\\"},\\"de nuke\\":{\\"team_a\\":\\"\\",\\"team_b\\":\\"\\"}}"}', NULL, '2017-06-16 00:05:59'),
(5, '5-midnight-turtles-rhyno-domynos', 'Vainglory', '2017-06-16 02:05:00', '0', '2', 1, 1, 'Midnight Turtles', 'http://themes.pixiesquad.com/pixiehuge/orange-elite/wp-content/uploads/2017/06/logo2.png', 2, 'Rhyno Domynos', 'http://themes.pixiesquad.com/pixiehuge/orange-elite/wp-content/uploads/2017/06/intz.png', 0, '{"tournament_name":"SL i-League StarSeries S3","tournament_description":"Season 2 April 2017","best_of":"3","read_article":"https:\\/\\/www.hltv.org\\/news\\/20717\\/sk-invited-to-esl-one-new-york","maps":"{\\"de dust 2\\":{\\"team_a\\":\\"\\",\\"team_b\\":\\"\\"},\\"de inferno\\":{\\"team_a\\":\\"\\",\\"team_b\\":\\"\\"},\\"de nuke\\":{\\"team_a\\":\\"\\",\\"team_b\\":\\"\\"}}"}', NULL, '2017-06-16 00:05:59'),
(6, '6-midnight-turtles-rhyno-domynos', 'Vainglory', '2017-06-16 02:05:00', '2', '0', 1, 1, 'Midnight Turtles', 'http://themes.pixiesquad.com/pixiehuge/orange-elite/wp-content/uploads/2017/06/logo2.png', 2, 'Rhyno Domynos', 'http://themes.pixiesquad.com/pixiehuge/orange-elite/wp-content/uploads/2017/06/intz.png', 0, '{"tournament_name":"SL i-League StarSeries S3","tournament_description":"Season 2 April 2017","best_of":"3","read_article":"https:\\/\\/www.hltv.org\\/news\\/20717\\/sk-invited-to-esl-one-new-york","maps":"{\\"de dust 2\\":{\\"team_a\\":\\"\\",\\"team_b\\":\\"\\"},\\"de inferno\\":{\\"team_a\\":\\"\\",\\"team_b\\":\\"\\"},\\"de nuke\\":{\\"team_a\\":\\"\\",\\"team_b\\":\\"\\"}}"}', NULL, '2017-06-16 00:05:59'),
(7, '7-midnight-turtles-rhyno-domynos', 'Vainglory', '2017-06-16 02:05:00', '0', '3', 1, 1, 'Midnight Turtles', 'http://themes.pixiesquad.com/pixiehuge/orange-elite/wp-content/uploads/2017/06/logo2.png', 2, 'Rhyno Domynos', 'http://themes.pixiesquad.com/pixiehuge/orange-elite/wp-content/uploads/2017/06/intz.png', 0, '{"tournament_name":"SL i-League StarSeries S3","tournament_description":"Season 2 April 2017","best_of":"3","read_article":"https:\\/\\/www.hltv.org\\/news\\/20717\\/sk-invited-to-esl-one-new-york","maps":"{\\"de dust 2\\":{\\"team_a\\":\\"\\",\\"team_b\\":\\"\\"},\\"de inferno\\":{\\"team_a\\":\\"\\",\\"team_b\\":\\"\\"},\\"de nuke\\":{\\"team_a\\":\\"\\",\\"team_b\\":\\"\\"}}"}', NULL, '2017-06-16 00:05:59'),
(8, '8-midnight-turtles-rhyno-domynos', 'Vainglory', '2017-06-16 02:05:00', '0', '0', 1, 1, 'Midnight Turtles', 'http://themes.pixiesquad.com/pixiehuge/orange-elite/wp-content/uploads/2017/06/logo2.png', 2, 'Rhyno Domynos', 'http://themes.pixiesquad.com/pixiehuge/orange-elite/wp-content/uploads/2017/06/intz.png', 0, '{"tournament_name":"SL i-League StarSeries S3","tournament_description":"Season 2 April 2017","best_of":"3","read_article":"https:\\/\\/www.hltv.org\\/news\\/20717\\/sk-invited-to-esl-one-new-york","maps":"{\\"de dust 2\\":{\\"team_a\\":\\"\\",\\"team_b\\":\\"\\"},\\"de inferno\\":{\\"team_a\\":\\"\\",\\"team_b\\":\\"\\"},\\"de nuke\\":{\\"team_a\\":\\"\\",\\"team_b\\":\\"\\"}}"}', NULL, '2017-06-16 00:05:59'),
(9, '9-midnight-turtles-rhyno-domynos', 'Vainglory', '2017-06-16 02:05:00', '0', '0', 1, 1, 'Midnight Turtles', 'http://themes.pixiesquad.com/pixiehuge/orange-elite/wp-content/uploads/2017/06/logo2.png', 2, 'Rhyno Domynos', 'http://themes.pixiesquad.com/pixiehuge/orange-elite/wp-content/uploads/2017/06/intz.png', 0, '{"tournament_name":"SL i-League StarSeries S3","tournament_description":"Season 2 April 2017","best_of":"3","read_article":"https:\\/\\/www.hltv.org\\/news\\/20717\\/sk-invited-to-esl-one-new-york","maps":"{\\"de dust 2\\":{\\"team_a\\":\\"\\",\\"team_b\\":\\"\\"},\\"de inferno\\":{\\"team_a\\":\\"\\",\\"team_b\\":\\"\\"},\\"de nuke\\":{\\"team_a\\":\\"\\",\\"team_b\\":\\"\\"}}"}', NULL, '2017-06-16 00:05:59'),
(10, '10-midnight-turtles-rhyno-domynos', 'Vainglory', '2017-06-16 02:05:00', '0', '0', 1, 1, 'Midnight Turtles', 'http://themes.pixiesquad.com/pixiehuge/orange-elite/wp-content/uploads/2017/06/logo2.png', 2, 'Rhyno Domynos', 'http://themes.pixiesquad.com/pixiehuge/orange-elite/wp-content/uploads/2017/06/intz.png', 0, '{"tournament_name":"SL i-League StarSeries S3","tournament_description":"Season 2 April 2017","best_of":"3","read_article":"https:\\/\\/www.hltv.org\\/news\\/20717\\/sk-invited-to-esl-one-new-york","maps":"{\\"de dust 2\\":{\\"team_a\\":\\"\\",\\"team_b\\":\\"\\"},\\"de inferno\\":{\\"team_a\\":\\"\\",\\"team_b\\":\\"\\"},\\"de nuke\\":{\\"team_a\\":\\"\\",\\"team_b\\":\\"\\"}}"}', NULL, '2017-06-16 00:05:59');
SQL;
$wpdb->query($sql);